### ISSUE TITLE
Travis not building VS project

### ISSUE THREAD

**Issue by Thomas1995** [Thomas1995/WorldCube#2]
Travis builds the project on Linux using the makefile, but I am afraid it might not be building the Visual Studio solution on Windows, even though I am not sure yet.

Please take a look in the .travis.yml file and its building logs on any commit.

**Comment by Thomas1995** [comment]
Okay, so it is confirmed now that it does not work. Take a look at this commit https://github.com/Thomas1995/WorldCube/commit/cf4cce1e5c8ce58d9cf0b6ba484af59fb8d7db0b.

I added some new cpps in the Makefile but not in the VS solution and Travis was okay with that.

**Comment by Thomas1995** [comment]
We added AppVeyor to test the build on Windows. All is good now.

**Comment by ionutcalofir** [comment]
Good work!
